### ISSUE TITLE
Crashes when trying to open article with no network connection

### ISSUE THREAD

**Issue by jonnyreeves** [longdivision/hex#3]
Steps to repo:

1. Open Hex from cold and fetch a list of articles
2. Return to the Android Launcher (background Hex)
3. Put device into flight mode 
4. Bring Hex to foreground
5. Select the same article

App will hard-crash.

**Comment by longdivision** [comment]
Apologies - that's an unpleasant bug! Thanks for reporting - taking a look into this

**Comment by jonnyreeves** [comment]
Appears to be related to network failures in general - I had a similar crash on the trail with flakey data after ~20 seconds or so trying to fetch comments for an article.

**Comment by longdivision** [comment]
The network failure handling in general is pretty flaky. Tightening it up in all areas as part of this issue.

**Comment by longdivision** [comment]
@jonnyreeves This fix is now published :)
