### ISSUE TITLE
Enable javascript in the browser 

### ISSUE THREAD

**Issue by jonnyreeves** [longdivision/hex#8]
So we can view embedded YouTube videos, etc.

**Comment by longdivision** [comment]
Oops - sorry about that! Quite an oversight 😶 

Put a fix in [v0.1.4](https://github.com/longdivision/hex/releases/tag/v0.1.4). Tested it with YouTube specifically and videos are playing nicely inline now. v0.1.4 was just deployed to the Play Store so should be with your shortly!

**Comment by jonnyreeves** [comment]
Nice one - got the update from the play store and it's working great! :)
